server.port: 80
server:
  ssl:
    enabled: false

logging:
  level:
    root: INFO
    org:
      apache:
        http:
          wire: ERROR
      springframework:
        boot:
          autoconfigure: ERROR
      hibernate:
        type: TRACE

dynamodb:
  endpoint: http://localhost:8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/littlegas
    username: postgres
    password: postgres
  jpa:
    hibernate:
      show-sql: true