server.port: 80
logging:
  file: /app/webapp.log
  level:
    root: ERROR
    org:
      apache:
        http:
          wire: ERROR
      springframework:
        boot:
          autoconfigure: ERROR
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_IUuEJR8MY
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
  datasource:
    url: jdbc:postgresql://hkfc.ct7jlst36sd2.ap-southeast-1.rds.amazonaws.com:5432/littlegas
    username: demo
    password: QlJZJOuFV0DJl134aky2

cloud:
  aws:
    stack:
      auto: false