server.port: 80

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_IUuEJR8MY

cloud:
  aws:
    stack:
      auto: false