server.port: 80
server:
  ssl:
    enabled: false

logging:
  level:
    root: debug

dynamodb:
  endpoint: http://localhost:8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      show-sql: true