package io.littlegashk.webapp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.data.annotation.Id;

@Data
@DynamoDBTable(tableName = "fchk")
@EqualsAndHashCode
public class District {

    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private DistrictId id;

    @DynamoDBHashKey(attributeName = "pid")
    @DynamoDBAutoGeneratedDefault("META")
    public String getPid(){
        return id==null?null:id.getPid();
    }

    public District setPid(String id){
        if(this.id==null){
            this.id=new DistrictId();
        }
        this.id.setPid(id);
        return this;
    }

    @DynamoDBRangeKey(attributeName = "sid")
    public String getDistrictId(){
        return id==null?null:id.getDistrictId();
    }

    public District setDistrictId(String districtId){
        if(this.id==null){
            this.id=new DistrictId();
        }
        this.id.setDistrictId(districtId);
        return this;
    }

    private String districtCode;

    public District setDistrictCode(String districtCode){
        this.districtCode = districtCode;
        return this;
    }

    @DynamoDBTypeConvertedJson
    private Statistics statistics;


}
