package io.littlegashk.webapp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;
import java.util.Set;

@DynamoDBTable(tableName = "littlegas")
@Data
public class Event {

    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private EventId id;


    @DynamoDBHashKey(attributeName = "pid")
    public String getTopicId(){
        return id==null?null:id.getTopicId();
    }

    public void setTopicId(String id){
        if(this.id==null){
            this.id=new EventId();
        }
        this.id.setTopicId(id);
    }

    @DynamoDBRangeKey(attributeName = "sid")
    @DynamoDBAutoGenerated(generator = EventIdGenerator.class)
    public String getEventId(){
        return id==null?null:id.getEventId();
    }

    public void setEventId(String recordId){
        if(this.id==null){
            this.id=new EventId();
        }
        this.id.setEventId(recordId);
    }



    //Arbitrary fields below, change as you want  :)

    @DynamoDbTypeConvertedLocalDate
    private LocalDate date;

    @DynamoDBTypeConvertedEnum
    private EventType eventType;


    @DynamoDBTypeConvertedEnum
    private PersonVote personVote;

    private String url;

    private String title;

    private String description;

    private int rating;

    @DynamoDBTypeConvertedJson
    private Set<String> upRaters;

    @DynamoDBTypeConvertedJson
    private Set<String> downRaters;

    private String createdBy;
}
