package io.littlegashk.webapp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.littlegashk.webapp.DynamoDbSchemaInitializer;
import lombok.*;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = DynamoDbSchemaInitializer.TABLE_LITTLEGAS)
@Data
@NoArgsConstructor
public class TagTopic {

    public TagTopic(TagTopicId id){
        this.id=id;
    }

    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private TagTopicId id;

    @DynamoDBHashKey(attributeName = "pid")
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "group-index")
    public String getTag(){
        return id == null?null: id.getTag();
    }

    public void setTag(String id){
        if(this.id == null){
            this.id =new TagTopicId();
        }
        this.id.setTag(id);
    }

    @DynamoDBRangeKey(attributeName = "sid")
    public String getTopicRecordId(){
        return id == null?null: id.getTopicRecordId();
    }

    public void setTopicRecordId(String topicRecordId){
        if(this.id == null){
            this.id =new TagTopicId();
        }
        this.id.setTopicRecordId(topicRecordId);
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "group-index")
    @DynamoDBAutoGeneratedDefault("TAG")
    private String group;

    @DynamoDBIgnore
    public String getTopicId(){
        return getTopicRecordId().split("\\|")[0];
    }

    @DynamoDBIgnore
    public String getRecordId(){
        return getTopicRecordId().split("\\|")[1];
    }

}
