package io.littlegashk.webapp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.util.List;

@DynamoDBTable(tableName = "littlegas")
@Data
public class Topic {

    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private TopicId id;

    @DynamoDBHashKey(attributeName = "pid")
    @DynamoDBAutoGeneratedKey
    public String getTopicId(){
        return id==null?null:id.getId();
    }

    public void setTopicId(String id){
        if(this.id==null){
            this.id=new TopicId();
        }
        this.id.setId(id);
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "meta-index")
    @DynamoDBRangeKey(attributeName = "sid")
    @DynamoDBAutoGeneratedDefault("META")
    public String getRecordId(){
        return id==null?null:id.getRecordId();
    }

    public void setRecordId(String recordId){
        if(this.id==null){
            this.id=new TopicId();
        }
        this.id.setRecordId(recordId);
    }

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "meta-index")
    private String group;



    // Arbitrary fields below, change as you want :)

    private String name;

    private String politicalAffiliation;

    private String imageUrl;

    @DynamoDBTypeConvertedJson
    private List<String> tags;

    private String background;

    private String socialMedia;

    @DynamoDBTypeConvertedEnum
    private PoliticalFaction politicalFaction;

    private boolean hidden;
}
