package io.littlegashk.webapp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.swagger.annotations.ApiModelProperty;
import jdk.jfr.EventType;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;
import java.util.List;

@DynamoDBTable(tableName = "littlegas")
@Data
public class Topic {

    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private TopicId id;

    @DynamoDBHashKey(attributeName = "pid")
    @DynamoDBAutoGeneratedKey
    public String getTopicId(){
        return id==null?null:id.getId();
    }

    public void setTopicId(String id){
        if(this.id==null){
            this.id=new TopicId();
        }
        this.id.setId(id);
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "meta-index")
    @DynamoDBRangeKey(attributeName = "sid")
    @DynamoDBAutoGeneratedDefault("TOP")
    public String getRecordId(){
        return id==null?null:id.getRecordId();
    }

    public void setRecordId(String recordId){
        if(this.id==null){
            this.id=new TopicId();
        }
        this.id.setRecordId(recordId);
    }


    //Any progress topics should NOT have group
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "meta-index")
    private String group;



    // Arbitrary fields below, change as you want :)

    private String title;

    private String summary;

    @DynamoDbTypeConvertedLocalDate
    private LocalDate eventDateTime;

    @DynamoDBTypeConvertedEnum
    private EntryType type;

    @DynamoDBTypeConvertedJson
    private List<String> relatedFiles;

    @DynamoDBTypeConvertedJson
    private List<String> relatedTopics;

    @DynamoDBTypeConvertedJson
    private List<String> references;

    @DynamoDBTypeConvertedJson
    private List<String> tags;
}
